version: '3.8'

services:
  database:
    container_name: database_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=100_SQLServer
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    expose:
      - 1433
    ports:
      - 1433:1433

  oracle_database:
    container_name: oracle_database
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1521:1521
    environment:
      - ORACLE_ALLOW_REMOTE=true
    volumes:
      - oracle_data:/u01/app/oracle/data

  backend:
    container_name: backend_csharp
    image: mcr.microsoft.com/dotnet/sdk:8.0
    restart: always
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://*:5074
      - ConnectionStrings__DefaultConnection=Server=database_sqlserver;Initial Catalog=guialocal;User ID=sa;Password=100_SQLServer;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
      - Google__ApiKey=AIzaSyBIBkZEexyq3td0QPGZHb9B_-s7-wm6y6I
      - Google__AuthUri=https://accounts.google.com/o/oauth2/v2/auth?scope=email&include_granted_scopes=true&response_type=token&state=state_parameter_passthrough_value&redirect_uri=http://localhost:4200&client_id=975758659668-65l4an4t4tbha9g5bian8dbp85nqspm6.apps.googleusercontent.com    
    volumes:
      - ./back:/app
    expose:
      - 5074
    ports:
      - 5074:5074
    command: sh -c 'dotnet restore && dotnet run'
    depends_on:
      - database
    
  frontend:
    container_name: frontend_angular
    image: node:18
    restart: always
    working_dir: /app
    volumes:
      - ./front:/app
    expose:
      - 4200
    ports:
      - 4200:4200
    command: sh -c 'npm install -g @angular/cli@13 && npm install && ng serve --host 0.0.0.0'
    depends_on:
      - backend


networks:
  guialoca-net:
    driver: bridge

volumes:
  sqlserver_data:
  oracle_data:
